### ISSUE TITLE
Fix Automated Testing

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/metalsmith-gathercontent#12]
- [ ] Have it detect auth json info from Environment Variables
- [ ] Move to CircleCI
- [ ] Add the auth vars to CircleCI
- [ ] Remove TravisCI

**Comment by thiagodemellobueno** [comment]
I suppose one thing we may want to consider is have it test against placeholder json somehow, then the whole thing becomes a lot simpler.

**Comment by RobLoach** [comment]
placeholder data would be good too. Mock it?
